Make Deploy job fail if rollback is triggered

diff --git a/.github/workflows/push-main.yaml b/.github/workflows/push-main.yaml
--- a/.github/workflows/push-main.yaml
+++ b/.github/workflows/push-main.yaml
@@ -82,5 +82,7 @@ jobs:
           if helm upgrade hackathon-api ./charts/hackathon-api --install --namespace default --set image.tag="$GITHUB_RUN_ID" --wait --timeout 1m; then
             echo "deployment succeeded!"
           else
+            echo "DEPLOYMENT FAILED! TRYING TO ROLLBACK"
             helm rollback hackathon-api --namespace default
+            exit 1
           fi
